---
title: "Thay đổi kích cỡ chữ trong đồ thị correlation"
author-title: <b>Biên soạn</b>
author: Duc Nguyen | Chuyên đào tạo kỹ năng R
site-url: https://www.tuhocr.com/
published-title: <b>Cập nhật</b> 
date: last-modified
date-format: "YYYY MMMM DD"
format:
  html:
    page-layout: full
    embed-resources: true
    anchor-sections: true
    smooth-scroll: true
engine: knitr
knitr:
  opts_chunk:
    R.options:
      width: 120
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, results='hide'}
knitr::opts_chunk$set(message = FALSE,  
                      warning = FALSE,
                      fig.width = 10,
                      fig.height = 6)   
```

```{r}
cor_ok <- readRDS("cor_ok.rds")

cor_ok <- as.matrix(cor_ok)

cor_ok

library("PerformanceAnalytics")
PerformanceAnalytics:::chart.Correlation(
  R = cor_ok,
  histogram = TRUE,
  method = "pearson"
)

# trace(PerformanceAnalytics:::chart.Correlation, edit = TRUE)

chart.Correlation_check <- function(R, histogram = TRUE, method = c(
                                      "pearson", "kendall",
                                      "spearman"
                                    ), cex_text = 3, cex_sign = 3, ...) {
  x <- checkData(R, method = "matrix")
  if (missing(method)) {
    method <- method[1]
  }
  cormeth <- method
  panel.cor <- function(
      x, y, digits = 2, prefix = "", use = "pairwise.complete.obs",
      method = cormeth, cex_text_ok = cex_text, cex_sign_ok = cex_sign, ...) {
    par(usr = c(0, 1, 0, 1))
    r <- cor(x, y, use = use, method = method)
    txt <- format(c(r, 0.123456789), digits = digits)[1]
    txt <- paste(prefix, txt, sep = "")

    test <- cor.test(as.numeric(x), as.numeric(y), method = method)
    Signif <- symnum(test$p.value,
      corr = FALSE, na = FALSE,
      cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1), symbols = c(
        "***",
        "**", "*", ".", " "
      )
    )
    text(0.5, 0.5, txt, cex = cex_text_ok)
    text(0.8, 0.8, Signif, cex = cex_sign_ok, col = 2)
  }
  f <- function(t) {
    dnorm(t, mean = mean(x), sd = sd.xts(x))
  }
  dotargs <- list(...)
  dotargs$method <- NULL
  rm(method)
  hist.panel <- function(x, ... = NULL) {
    par(new = TRUE)
    hist(x,
      col = "light gray", probability = TRUE, axes = FALSE,
      main = "", breaks = "FD"
    )
    lines(density(x, na.rm = TRUE), col = "red", lwd = 1)
    rug(x)
  }
  if (histogram) {
    pairs(x,
      gap = 0, lower.panel = panel.smooth, upper.panel = panel.cor,
      diag.panel = hist.panel
    )
  } else {
    pairs(x, gap = 0, lower.panel = panel.smooth, upper.panel = panel.cor)
  }
}

chart.Correlation_check(
  R = cor_ok,
  histogram = TRUE,
  method = "pearson",
  cex_text = 4,
  cex_sign = 4
)
```

**Dataset: [cor_ok.rds](https://applyr.netlify.app/blog/cor_ok.rds)**

**Link: [Thay đổi kích cỡ chữ trong đồ thị correlation](https://applyr.netlify.app/blog/cor_blog.html)**