project:
  type: book

book:
  title: "Thống kê sinh học: Từ lý thuyết đến ứng dụng"
  author: "Duc Nguyen | Founder of tuhocr.com"
  site-url: https://www.tuhocr.com/
  date: last-modified
  date-format: "[Cập nhập:] YYYY MMMM DD"
  cover-image: cover.png
  favicon: favicon.png
  # comments:
  #   hypothesis:
  #     theme: clean
  chapters:
    - index.qmd
    - part: co-so-ly-thuyet.qmd
      chapters:
        - khoang-tin-cay.qmd
        # - phan-tich-anova-2-yeu-to-kieu-rcbd-trong-r.qmd
        - huong-dan-phan-tich-t-test-trong-r.qmd
        - phan-tich-anova-2-yeu-to-trong-r.qmd
        - so-sanh-ket-qua-giua-parametric-va-non-parametric-anova.qmd
        - phan-tich-ancova-trong-r.qmd
        - khai-niem-bootstrap-qua-vi-du-tinh-trung-binh-mau.qmd
        - bo-tri-thi-nghiem-toi-uu-hoa-bang-r.qmd
        - workflow-phan-tich-thong-ke-qua-dataset-iris.qmd
        # - huong-dan-phan-tich-logistic-regression.qmd
        - example-partial-least-squares-and-principal-component-regression.qmd
    - part: "Kỹ thuật xử lý dữ liệu"
      chapters:
        - huong-dan-convert-tu-csv-qua-tsv-trong-r.qmd
        - huong-dan-cach-lam-tron-so-trong-r.qmd
        - huong-dan-show-all-data-tren-console.qmd
    - references.qmd
    
  sidebar:
    style: "docked"
    search: true
    title: "<a href='https://thongkesinhhoc.quarto.pub/'>Thống kê sinh học: Từ lý thuyết đến ứng dụng</a>"
          
bibliography: references.bib

format:
  html:
    toc: false
    theme: default
    page-layout: full
  # pdf:
  #   documentclass: scrreprt



