# **Các lệnh đồ thị căn bản sử dụng Base R Graphics** {.unnumbered}

```{r, include=FALSE}
options(width = 1200)
knitr::opts_chunk$set(fig.width = 8, fig.height = 6, warning = FALSE, message = FALSE)
```

### 1. Dữ liệu minh họa

```{r}
# https://tuhocr.netlify.app/flashr/loop/doanh_thu_ban_hang.xlsx
library(readxl)

doanh_thu <- readxl::read_excel("doanh_thu_ban_hang.xlsx")

doanh_thu

doanh_thu <- as.data.frame(doanh_thu)

doanh_thu

```



### 2. Dữ liệu thực tế

```{r}
# https://tuhocr.netlify.app/flashr/loop/crop_production_all_data.rds
# https://tuhocr.netlify.app/flashr/loop/FAOSTAT_data_3-21-2023.csv
df_1 <- readRDS("crop_production_all_data.rds")
df_2 <- read.csv("FAOSTAT_data_3-21-2023.csv") 

library(tuhocr)
rice <- tuhocr::extract_faostat(input_rds = df_1,
                        input_region = df_2,
                        input_item = "Rice")

head(rice)
dim(rice)
```

**Chọn riêng dữ liệu gạo của Việt Nam**

```{r}
rice |> subset(area == "Viet Nam") -> rice_vietnam

row.names(rice_vietnam) <- NULL

rice_vietnam

class(rice_vietnam)
```

### 3. Vẽ đồ thị cột

```{r}
barplot(production ~ year, data = rice_vietnam)
```






















### Vẽ đồ thị đường